# Generated by Django 3.2 on 2022-12-18 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicallocation_historicaluserdate_location_userdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallocation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Location', 'verbose_name_plural': 'historical Locations'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserdate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User Data', 'verbose_name_plural': 'historical Datas'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='userdate',
            options={'verbose_name': 'User Data', 'verbose_name_plural': 'Datas'},
        ),
        migrations.AlterField(
            model_name='historicaluserdate',
            name='telf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telf'),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='telf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telf'),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
