country_support = (
        ('CU', 'Cuba'),
        ('US', 'USA'),
        ('ES', 'Spain'),
        ('GB', 'United Kingdom'),
    )

rank_account = (
        (0, 'Usuarios basicos'),
        (10, 'Usuarios con cuenta Business'),
        (20, 'Usuarios Promotor'),
        (30, 'Administracion y Soporte'),
    )

type_locators = (
        ('rs','Redes Sociales'),
        ('px','Plataformas Expecializadas'),
        ('df','Direcciones Fisicas'),
    )

social_locators = (
        ('fb','Facebook'),
        ('tw','Twitter'),
        ('lk','Linkedin'),
        ('rd','Reddit'),
        ('so','Stack Overflow'),
        ('bg','Blogger'),
        ('ab','Airbnb'),
    )

payment_status = (
        ('proc', 'En proceso'),
        ('canc', 'Cancelado'),
        ('rech', 'Rechazado'),
        ('paga', 'Pagado'),
        ('rein', 'Reintegrado'),
        ('devo', 'Por devolver'),
        ('perd', 'Perdido'),
    )

token_uso = (
        ('register', 'Registro de Cuenta'),
        ('reset', 'Resetear Contraseña'),
        ('support', 'Verificación de Soporte'),
        ('tike', 'Tike de Reporte'),
    )

article_status = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

apps_status = (
        (0, 'Desarrollo: sin usar'),
        (10, 'Desarrollo: haciendo pruebas'),
        (20, 'Produccion: estado beta'),
        (30, 'Produccion: estado stable'),
    )

apps_uso = (
        (0, 'Usuarios basicos'),
        (1, 'Usuarios con cuenta Business'),
        (2, 'Usuarios Promotor'),
        (3, 'Administracion y Soporte'),
    )

clasificados_redes = (
        ('all', 'compra venta de todo'),
        ('cvt1', 'Ropa / Calzados'),
        ('cvt2', 'Electrodomésticos'),
        ('cvt3', 'Ferretería / Construcción'),
        ('cvt4', 'Aseo / Perfumería'),
        ('cvt5', 'Antigüedades / Colecciones'),
        ('cvt6', 'Libros / Revistas'),
        ('cvt7', 'Mascotas'),
        ('cvt8', 'Muebles'),
        ('srv1', 'Peluquería / Barbería / Belleza'),
        ('srv2', 'Clases / Cursos'),
        ('srv3', 'Construcción / Mantenimiento'),
        ('srv4', 'Diseño / Impresiones /Decoración'),
        ('srv5', 'Escritura / Traducción'),
        ('srv6', 'Gimnasio / Masaje / Entrenador'),
        ('srv7', 'Guarderías / Limpieza / Doméstico'),
        ('srv8', 'Informática / Programación'),
        ('srv9', 'Gastronomía / Restaurantes /Paladares / Cafeterías'),
        ('srv10', 'Técnico / Reparaciones'),
        ('srv11', 'Trámites / Promociones'),
        ('srv12', 'Video / Fotografía'),
        ('srv13', 'Relojero / Joyero'),
        ('srv14', 'Reparación Electrónica'),
        ('srv15', 'Películas / Series / Videos'),
        ('viv1', 'Casas en venta'),
        ('viv2', 'Alquiler por mes/año'),
        ('viv3', 'Renta por horas/días'),
        ('viv4', 'Terrenos / Garajes'),
        ('trans1', 'Carros'),
        ('trans2', 'Motos'),
        ('trans3', 'Bicicletas'),
        ('trans4', 'Piezas / Accesorios'),
        ('trans5', 'Taxi / Rentas'),
        ('trans6', 'Taller / Reparaciones'),
        ('pc1', 'PC de Escritorio'),
        ('pc2', 'Laptop'),
        ('pc3', 'Microprocesador'),
        ('pc4', 'Monitor'),
        ('pc5', 'Motherboard'),
        ('pc6', 'Memoria RAM / FLASH'),
        ('pc7', 'Disco Duro Interno / Externo'),
        ('pc8', 'Chasis / Fuente'),
        ('pc9', 'Tarjeta de Video'),
        ('pc10', 'Tarjeta de Sonido / Bocinas'),
        ('pc11', 'Quemador / Lector DVD/CD'),
        ('pc12', 'Backup / UPS'),
        ('pc13', 'Impresora / Cartuchos'),
        ('pc14', 'Modem / Wifi / Red'),
        ('pc15', 'Webcam / Microfono / Audífono'),
        ('pc16', 'Teclado / Mouse'),
        ('pc17', 'Internet / Email'),
        ('pc18', 'CD / DVD Virgen'),
        ('cel1', 'Celulares en venta'),
        ('cel2', 'Piezas / Accesorios'),
        ('cel3', 'Software / Reparación'),
        ('consl1', 'Consolas en venta'),
        ('consl2', 'Accesorios / Consolas'),
        ('consl3', 'Juegos / Reparación'),
    )

#Del "CIIU REVISIÓN 4" escogimos division y subclases
brand_subsector = (
        ('A01', 'AGRICULTURA, GANADERÍA, CAZA Y ACTIVIDADES DE SERVICIOS CONEXAS'),
        ('A02', 'SILVICULTURA Y EXTRACCIÓN DE MADERA'),
        ('A03', 'PESCA Y ACUICULTURA'),
        ('B01', 'EXTRACCIÓN DE CARBÓN DE PIEDRA Y LIGNITO'),
        ('B02', 'EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL'),
        ('B03', 'EXTRACCIÓN DE MINERALES METALÍFEROS'),
        ('B04', 'EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS'),
        ('B05', 'ACTIVIDADES DE SERVICIOS DE APOYO PARA LA EXPLOTACIÓN DE MINAS Y CANTERAS'),
        ('C01', 'ELABORACIÓN DE PRODUCTOS ALIMENTICIOS'),
        ('C02', 'ELABORACIÓN DE BEBIDAS'),
        ('C03', 'ELABORACIÓN DE PRODUCTOS DE TABACO'),
        ('C04', 'FABRICACIÓN DE PRODUCTOS TEXTILES'),
        ('C05', 'FABRICACIÓN DE PRENDAS DE VESTIR'),
        ('C06', 'FABRICACIÓN DE CUEROS Y PRODUCTOS CONEXOS'),
        ('C07', 'FABRICACIÓN DE PRODUCTOS DE MADERA Y CORCHO, EXCEPTO MUEBLES; FABRICACIÓN DE ARTÍCULOS DE PAJA Y DE MATERIALES TRENZABLES'),
        ('C08', 'FABRICACIÓN DE PAPEL Y DE PRODUCTOS DE PAPEL'),
        ('C09', 'IMPRESIÓN Y REPRODUCCIÓN DE GRABACIONES'),
        ('C10', 'FABRICACIÓN DE COQUE Y DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO'),
        ('C11', 'FABRICACIÓN DE SUBSTANCIAS Y PRODUCTOS QUÍMICOS'),
        ('C12', 'FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS, SUSTANCIAS QUÍMICAS MEDICINALES Y PRODUCTOS BOTÁNICOS DE USO FARMACÉUTICO'),
        ('C13', 'FABRICACIÓN DE PRODUCTOS DE CAUCHO Y PLÁSTICO'),
        ('C14', 'FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS'),
        ('C15', 'FABRICACIÓN DE METALES COMUNES'),
        ('C16', 'FABRICACIÓN DE PRODUCTOS ELABORADOS DE METAL, EXCEPTO MAQUINARIA Y EQUIPO'),
        ('C17', 'FABRICACIÓN DE PRODUCTOS DE INFORMÁTICA, ELECTRÓNICA Y ÓPTICA'),
        ('C18', 'FABRICACIÓN DE EQUIPO ELÉCTRICO'),
        ('C19', 'FABRICACIÓN DE MAQUINARIA Y EQUIPO N.C.P'),
        ('C20', 'FABRICACIÓN DE VEHÍCULOS AUTOMOTORES, REMOLQUES Y SEMIRREMOLQUES'),
        ('C21', 'FABRICACIÓN DE OTROS TIPOS DE EQUIPOS DE TRANSPORTE'),
        ('C22', 'FABRICACIÓN DE MUEBLES'),
        ('C23', 'OTRAS INDUSTRIAS MANUFACTURERAS'),
        ('C24', 'REPARACIÓN E INSTALACIÓN DE MAQUINARIA Y EQUIPO'),
        ('D01', 'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO'),
        ('E01', 'CAPTACIÓN, TRATAMIENTO Y DISTRIBUCIÓN DE AGUA'),
        ('E02', 'EVACUACIÓN DE AGUAS RESIDUALES'),
        ('E03', 'RECOLECCIÓN, TRATAMIENTO Y ELIMINACIÓN DE DESECHOS, RECUPERACIÓN DE MATERIALES'),
        ('E04', 'ACTIVIDADES DE DESCONTAMINACIÓN Y OTROS SERVICIOS DE  GESTIÓN DE DESECHOS'),
        ('F01', 'CONSTRUCCIÓN DE EDIFICIOS'),
        ('F02', 'OBRAS DE INGENIERÍA CIVIL'),
        ('F03', 'ACTIVIDADES ESPECIALIZADAS DE LA CONSTRUCCIÓN'),
        ('G01', 'COMERCIO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS'),
        ('G02', 'COMERCIO AL POR MAYOR, EXCEPTO EL DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS'),
        ('G03', 'COMERCIO AL POR MENOR, EXCEPTO EL DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS'),
        ('H01', 'TRANSPORTE POR VÍA TERRESTRE Y POR TUBERÍAS'),
        ('H02', 'TRANSPORTE POR VÍA ACUÁTICA'),
        ('H03', 'TRANSPORTE POR VÍA AÉREA'),
        ('H04', 'ALMACENAMIENTO Y ACTIVIDADES DE APOYO AL TRANSPORTE'),
        ('H05', 'ACTIVIDADES POSTALES Y DE MENSAJERÍA'),
        ('I01', 'ACTIVIDADES DE ALOJAMIENTO'),
        ('I02', 'SERVICIO DE ALIMENTO Y BEBIDA'),
        ('J01', 'ACTIVIDADES DE PUBLICACIÓN'),
        ('J02', 'ACTIVIDADES DE PRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VÍDEOS Y PROGRAMAS DE TELEVISIÓN, GRABACIÓN DE SONIDO Y EDICIÓN DE MÚSICA'),
        ('J03', 'ACTIVIDADES DE PROGRAMACIÓN Y TRANSMISIÓN'),
        ('J04', 'TELECOMUNICACIONES'),
        ('J05', 'PROGRAMACIÓN INFORMÁTICA, CONSULTORÍA DE INFORMÁTICA Y ACTIVIDADES CONEXAS'),
        ('J06', 'ACTIVIDADES DE SERVICIOS DE INFORMACIÓN'),
        ('K01', 'ACTIVIDADES DE SERVICIOS FINANCIEROS, EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES'),
        ('K02', 'SEGUROS, REASEGUROS Y FONDOS DE PENSIONES, EXCEPTO LOS PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA'),
        ('K03', 'ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS'),
        ('L01', 'ACTIVIDADES INMOBILIARIAS'),
        ('M01', 'ACTIVIDADES JURÍDICAS Y DE CONTABILIDAD'),
        ('M02', 'ACTIVIDADES DE OFICINAS PRINCIPALES; ACTIVIDADES DE CONSULTORÍA DE GESTIÓN'),
        ('M03', 'ACTIVIDADES DE ARQUITECTURA E INGENIERÍA; ENSAYOS Y ANÁLISIS TÉCNICOS'),
        ('M04', 'INVESTIGACIÓN CIENTÍFICA Y DESARROLLO'),
        ('M05', 'PUBLICIDAD Y ESTUDIOS DE MERCADO'),
        ('M06', 'OTRAS ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS'),
        ('M07', 'ACTIVIDADES VETERINARIAS'),
        ('N01', 'ACTIVIDADES DE ALQUILER Y ARRENDAMIENTO'),
        ('N02', 'ACTIVIDADES DE EMPLEO'),
        ('N03', 'ACTIVIDADES DE AGENCIAS DE VIAJES, OPERADORES TURÍSTICOS, SERVICIOS DE RESERVAS Y ACTIVIDADES CONEXAS'),
        ('N04', 'ACTIVIDADES DE SEGURIDAD E INVESTIGACIÓN'),
        ('N05', 'ACTIVIDADES DE SERVICIOS A EDIFICIOS Y PAISAJISMO'),
        ('N06', 'ACTIVIDADES ADMINISTRATIVAS Y DE APOYO DE OFICINA Y OTRAS ACTIVIDADES DE APOYO A LAS EMPRESAS'),
        ('P01', 'ENSEÑANZA'),
        ('Q01', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA'),
        ('Q02', 'ACTIVIDADES DE ATENCIÓN EN INSTITUCIONES'),
        ('Q03', 'ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO'),
        ('R01', 'ACTIVIDADES CREATIVAS, ARTÍSTICAS Y DE ENTRETENIMIENTO'),
        ('R02', 'ACTIVIDADES DE BIBLIOTECAS, ARCHIVOS, MUSEOS Y OTRAS ACTIVIDADES CULTURALES'),
        ('R03', 'ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS'),
        ('R04', 'ACTIVIDADES DEPORTIVAS, DE ESPARCIMIENTO Y RECREATIVAS'),
        ('S01', 'REPARACIÓN DE COMPUTADORES Y DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS'),
        ('S02', 'OTRAS ACTIVIDADES DE SERVICIOS PERSONALES'),
        ('T01', 'ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO'),
        ('T02', 'ACTIVIDADES NO DIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO'),
    )
