# Generated by Django 3.2 on 2022-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_stock_thumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo'),
        ),
    ]
